app/cf/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("extensions.urls")),
    # path("users/", include("users.urls")),
    path("accounts/", include("allauth.urls")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/extensions/urls.py
from django.urls import path

from .views import (
    EnquireCreateView,
    EnquiryDetailView,
    EnquiryListView,
    EnquiryPaymentCreateView,
    EnquiryPaymentDetailView,
    EnquiryRemarksCreateFormView,
    SubsequentPermitCreateView,
    SubsequentPermitDetailView,
)

urlpatterns = [
    path("", EnquiryListView.as_view(), name="enquiry-list"),
    path("create/", EnquireCreateView.as_view(), name="enquiry-create"),
    path("detail/<int:pk>/", EnquiryDetailView.as_view(), name="enquiry-detail"),
    path(
        "enquiry/<int:enquiry_id>/add_comment/",
        EnquiryRemarksCreateFormView.as_view(),
        name="add-enquiry-remark",
    ),
    path(
        "subsequent-permit/create/<int:enquiry_id>/",
        SubsequentPermitCreateView.as_view(),
        name="subsequent-permit-create",
    ),
    path(
        "subsequent-permit/detail/<int:pk>/",
        SubsequentPermitDetailView.as_view(),
        name="subsequent-permit-detail",
    ),
    path(
        "enquiry-payment/create/<int:pk>/",
        EnquiryPaymentCreateView.as_view(),
        name="enquiry-payment-create",
    ),
    path(
        "enquiry-payment/detail/<int:pk>/",
        EnquiryPaymentDetailView.as_view(),
        name="enquiry-payment-detail",
    ),
]

app/extensions/models.py
from decimal import Decimal

from django.db import models
from django.shortcuts import reverse
from users.models import User


class PortOfEntry(models.Model):
    ENTRY_TYPE_CHOICES = (
        ("AIR", "AIR"),
        ("SEA", "SEA"),
    )
    name = models.CharField(max_length=255)
    code = models.CharField(max_length=255, blank=True, null=True)
    entry_type = models.CharField(
        max_length=3, choices=ENTRY_TYPE_CHOICES, default=ENTRY_TYPE_CHOICES[0][0]
    )

    class Meta:
        verbose_name_plural = "Ports of entry"

    def __str__(self):
        if not self.code:
            return f"{self.name} - {self.entry_type}"
        return f"{self.name} - {self.code} - {self.entry_type.upper()}"


class MaritalStatus(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        verbose_name_plural = "marital statuses"

    def __str__(self):
        return self.name


class Enquiry(models.Model):
    PURPOSE_CHOICES = [
        ("Tourism", "Tourism"),
        ("Business", "Business"),
        ("Education", "Education"),
        ("Medical Treatment", "Medical Treatment"),
        ("Family Visit", "Family Visit"),
        ("Other", "Other"),
    ]

    MEANS_OF_SUPPORT_CHOICES = [
        ("Personal Savings", "Personal Savings"),
        ("Sponsorship", "Sponsorship"),
        ("Employment", "Employment"),
        ("Other", "Other"),
    ]
    img = models.ImageField(
        upload_to="enquiry_images", blank=True, null=True, verbose_name="photo"
    )
    surname = models.CharField(max_length=255)
    christian_names = models.CharField(max_length=255)
    pob = models.CharField(max_length=255, verbose_name="place of birth")
    dob = models.DateField(verbose_name="date of birth")
    nationality = models.CharField(max_length=255)
    foreign_address = models.CharField(max_length=255)
    foreign_address1 = models.CharField(max_length=255)
    phone = models.CharField(max_length=255)
    email = models.EmailField(blank=True)
    occu = models.CharField(max_length=255, verbose_name="occupation")
    marital_status = models.ForeignKey(
        MaritalStatus, on_delete=models.PROTECT, related_name="marital_statuses"
    )
    ppn = models.CharField(max_length=255, verbose_name="passport number")
    passport = models.FileField(upload_to="passport_images", blank=True, null=True)
    pp_exp = models.DateField(verbose_name="passport expiry date")
    pp_issue_place = models.CharField(
        max_length=255, verbose_name="passport place issued"
    )
    pp_issue_date = models.DateField(verbose_name="passport issued date")
    arrival_date = models.DateField()
    arrival_place = models.ForeignKey(
        PortOfEntry,
        on_delete=models.PROTECT,
        related_name="ports_of_entry",
        help_text="Air/Sea Port",
    )
    arrived_from = models.CharField(max_length=255)
    arrived_via = models.CharField(
        max_length=255, help_text="Straight flight/Last stop off"
    )
    pov = models.CharField(
        max_length=255, verbose_name="purpose of visit", choices=PURPOSE_CHOICES
    )
    host_id_no = models.CharField(
        max_length=255, verbose_name="host ID number", blank=True, null=True
    )
    host_id = models.FileField(
        upload_to="host_id_images/", blank=True, null=True, verbose_name="Host ID"
    )
    hotel_res = models.FileField(
        upload_to="hotel_res_images/",
        blank=True,
        null=True,
        verbose_name="Hotel reservations",
    )
    rental_agreement = models.FileField(
        upload_to="rental_agreement_images/", blank=True, null=True
    )
    work_permit = models.FileField(
        upload_to="work_permit_images/", blank=True, null=True
    )
    exemption = models.FileField(upload_to="exemption_images/", blank=True, null=True)
    imm_offr = models.ForeignKey(User, on_delete=models.PROTECT, related_name='officers', null=True, blank=True, verbose_name="immigration officer", default=1)
    time_granted_from = models.DateField(verbose_name="from")
    time_granted_to = models.DateField(verbose_name="to")
    time_granted = models.CharField(max_length=255)
    tempt_res = models.BooleanField(default=False, verbose_name="temporary resident")
    perm_res = models.BooleanField(default=False, verbose_name="permanent resident")
    address_in_st_lucia = models.CharField(
        max_length=255, verbose_name="Address in St Lucia"
    )
    tel_in_st_lucia = models.CharField(
        max_length=255, verbose_name="Telephone in St Lucia"
    )

    means_of_support = models.CharField(
        max_length=255, choices=MEANS_OF_SUPPORT_CHOICES
    )
    ticket_no = models.CharField(max_length=255, verbose_name="ticket number")
    ticket = models.FileField(upload_to="tickets/", blank=True, null=True)
    validity = models.DateField(
        verbose_name="valid until", help_text="Ticket valid until"
    )
    created_by = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name="enquire_created_by",
        null=True,
        blank=True,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    updated_by = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name="enquire_updated_by",
        null=True,
        blank=True,
    )

    class Meta:
        ordering = ["-arrival_date"]
        verbose_name_plural = "enquiries"

    def get_enquiry_cost(self):
        cost = Decimal(self.time_granted) * Decimal(200 / 30)
        return f"{cost:.2f}"

    def get_absolute_url(self):
        return reverse("enquiry-detail", kwargs={"pk": self.pk})

    def __str__(self):
        return f"{self.surname.title()} {self.christian_names.title()} - {self.ppn.upper()}"


class EnquiryRemark(models.Model):
    """
    This is the model for the remarks
    """

    enquiry = models.ForeignKey(
        Enquiry, on_delete=models.PROTECT, related_name="enquiry_remarks"
    )
    remarks = models.TextField()
    created_by = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name="remarks_created_by",
        null=True,
        blank=True,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    updated_by = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name="remarks_updated_by",
        null=True,
        blank=True,
    )

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.enquiry.surname} {self.enquiry.christian_names} - {self.enquiry.ppn}"


class PaymentType(models.Model):
    name = models.CharField(max_length=255)
    desc = models.TextField(blank=True)

    def __str__(self):
        return self.name


class EnquiryPayment(models.Model):
    """
    This is the model for the payment
    """

    enquiry = models.ForeignKey(
        Enquiry, on_delete=models.PROTECT, related_name="enquiry_payments"
    )
    payment_type = models.ForeignKey(
        PaymentType,
        on_delete=models.PROTECT,
        related_name="payment_types",
        null=True,
        blank=True,
    )
    payment_amount = models.DecimalField(decimal_places=2, max_digits=10, default=0.0)
    payment_date = models.DateField(blank=True, null=True)
    receipt_no = models.CharField(
        max_length=255, verbose_name="receipt number", null=True, blank=True
    )
    created_by = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name="enquiry_payment_created_by",
        null=True,
        blank=True,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    updated_by = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name="enquiry_payment_updated_by",
        null=True,
        blank=True,
    )

    def get_absolute_url(self):
        return reverse("enquiry-payment-detail", kwargs={"pk": self.pk})

    def __str__(self):
        return f"{self.enquiry} - {self.payment_amount}"


class SubsequentPermit(models.Model):
    """
    This is the model for the subsequent permits
    """

    enquiry = models.ForeignKey(
        Enquiry, on_delete=models.PROTECT, related_name="subsequent_permits"
    )
    length_of_stay = models.CharField(max_length=255, blank=True)
    time_granted = models.CharField(max_length=255)
    time_granted_from = models.DateField(verbose_name="from")
    time_granted_to = models.DateField(verbose_name="to")
    granted_by = models.ForeignKey(
        User, on_delete=models.PROTECT, related_name="granted_by"
    )
    created_by = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name="subsequent_permit_created_by",
        null=True,
        blank=True,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    updated_by = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name="subsequent_permit_updated_by",
        null=True,
        blank=True,
    )

    def get_absolute_url(self):
        return reverse("subsequent-permit-detail", kwargs={"pk": self.pk})

    def get_subsequent_permit_cost(self):
        cost = Decimal(self.time_granted) * Decimal(200 / 30)
        return f"{cost:.2f}"

    def __str__(self):
        return f"{self.enquiry.surname} {self.enquiry.christian_names} - {self.enquiry.ppn}"


class SubsequentPermitRemark(models.Model):
    """
    This is the model for the remarks
    """

    subsequent_permit = models.ForeignKey(
        SubsequentPermit,
        on_delete=models.PROTECT,
        related_name="subsequent_permit_remarks",
    )
    remarks = models.TextField()
    created_by = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name="subsequent_permit_remark_created_by",
        null=True,
        blank=True,
    )

app/extensions/forms.py
from django import forms

from .models import (
    Enquiry,
    EnquiryPayment,
    EnquiryRemark,
    SubsequentPermit,
    SubsequentPermitPayment,
)


class EnquiryPaymentCreateForm(forms.ModelForm):
    class Meta:
        model = EnquiryPayment
        fields = "__all__"
        exclude = ["created_by", "updated_by"]
        widgets = {
            "payment_date": forms.TextInput(attrs={"type": "date"}),
        }


class SubsequentPermitPaymentCreateForm(forms.ModelForm):
    class Meta:
        model = SubsequentPermitPayment
        fields = "__all__"
        exclude = ["created_by", "updated_by"]
        widgets = {
            "subsequent_permit": forms.HiddenInput(),
            # "granted_by": forms.HiddenInput(),
            "payment_date": forms.TextInput(attrs={"type": "date"}),
            # "time_granted_to": forms.TextInput(attrs={"type": "date"}),
        }


class SubsequentPermitPaymentUpdateForm(forms.ModelForm):
    class Meta:
        model = SubsequentPermitPayment
        fields = "__all__"
        exclude = ["created_by", "updated_by"]
        # widgets = {
        #     "enquiry": forms.HiddenInput(),
        #     "granted_by": forms.HiddenInput(),
        #     "time_granted_from": forms.TextInput(attrs={"type": "date"}),
        #     "time_granted_to": forms.TextInput(attrs={"type": "date"}),
        # }


class SubsequentPermitCreateForm(forms.ModelForm):
    class Meta:
        model = SubsequentPermit
        fields = "__all__"
        exclude = ["created_by", "updated_by"]
        widgets = {
            "enquiry": forms.HiddenInput(),
            "granted_by": forms.HiddenInput(),
            "time_granted_from": forms.TextInput(attrs={"type": "date"}),
            "time_granted_to": forms.TextInput(attrs={"type": "date"}),
        }


class EnquiryRemarksCreateForm(forms.ModelForm):
    class Meta:
        model = EnquiryRemark
        fields = "__all__"
        exclude = ["created_by", "updated_by"]
        widgets = {
            "enquiry": forms.HiddenInput(),
            "remarks": forms.Textarea(attrs={"rows": 4}),
        }


class EnquiryCreateForm(forms.ModelForm):
    class Meta:
        model = Enquiry
        fields = "__all__"
        exclude = ["created_by", "updated_by"]
        widgets = {
            "dob": forms.TextInput(attrs={"type": "date"}),
            "pp_exp": forms.TextInput(attrs={"type": "date"}),
            "pp_issue_date": forms.TextInput(attrs={"type": "date"}),
            "arrival_date": forms.TextInput(attrs={"type": "date"}),
            "time_granted_from": forms.TextInput(attrs={"type": "date"}),
            "time_granted_to": forms.TextInput(
                attrs={"type": "date", "disabled": True}
            ),
            "validity": forms.TextInput(attrs={"type": "date"}),
        }

app/templates/extensions/enquiry_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block head_title %}
Form
{% endblock head_title %}


{% block content %}
<div class="container">
    <h1>Form</h1>
    <hr>
    <div class="col-lg-6 mx-auto p-5 m-5 rounded-4 shadow">
        <form action=""
            method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form|crispy}}
            <my-5 class="my-5 d-grid">
                <button class="btn btn-lg btn-outline-dark rounded"
                    type="submit">Submit</button>
            </my-5>
        </form>
    </div>
</div>

{% endblock content %}

app/templates/extensions/enquiry_list.html
{% extends 'base.html' %}

{% load humanize %}
{% load crispy_forms_tags %}

{% block head_title %}
Enquiries
{% endblock head_title %}


{% block content %}

<div class="p-5">

    <div class="row">
        <div class="col-lg-2 mx-auto">
            <div
                class="h3 border border-3 border-dark rounded-4 p-5 text-dark text-center shadow">
                <span title="total">Enquiries ({{object_list.count}})</span>
            </div>
        </div>
    </div>
    <div class="d-flex justify-content-center p-5">
        <div class="mx-5 pt-2">
            <a title="add cheque"
                class="text-decoration-none text-dark"
                href="{% url 'enquiry-create' %}">
                <span class="material-symbols-outlined fs-1">
                    add_circle
                </span>
            </a>
        </div>
        <div class="col-lg-6">
            <form action=""
                method="get">
                <input type="search"
                    class="form-control form-control-lg border border-3 rounded-pill"
                    autofocus="autofocus"
                    placeholder="Search"
                    name="enquiries"
                    id="cheque_id_id">
            </form>
        </div>
        <div class="mx-3 pt-2">
            <a class="small text-muted"
                href="/">reset</a>
        </div>

    </div>

    <div class="table-responsive">
        <table class="mt-3 table table-sm table-hover table-bordered">
            <thead>
                <tr class="table-dark">
                    <th scope="col">#</th>
                    <th scope="col">Applicant</th>
                    <th scope="col">Arrival</th>
                    <th scope="col">Purpose of visit</th>
                    <th scope="col">Time granted</th>
                    <th scope="col">Means of support</th>
                    <th scope="col">Valid Until</th>
                </tr>
            </thead>
            <tbody>
                {% for ob in object_list %}
                <tr>
                    <th scope="row">{{forloop.counter}}</th>
                    <td><a class="text-dark" href="{{ ob.get_absolute_url }}">{{ob.surname}}, {{ob.christian_names}}</a></td>
                    <td>Arriving {{ob.arrival_date}}
                        Via: {{ob.arrival_place}}
                        ({{ob.arrival_place.entry_type}})
                        {{od.arrived_from}}
                        {{ob.arrived_via}}</td>
                    <td>{{ob.pov}}</td>
                    <td>{{ob.time_granted}}</td>
                    <td>{{ob.means_of_support}}</td>
                    <td>{{ob.ticket_no|upper}} {{ob.validity}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock content %}

app/templates/extensions/enquirypayment_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block head_title %}
Form
{% endblock head_title %}


{% block content %}
<div class="container">
    <h1>Form</h1>
    <hr>
    <div class="col-lg-6 mx-auto p-5 m-5 rounded-4 shadow">
        <form action=""
            method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form|crispy}}
            <my-5 class="my-5 d-grid">
                <button class="btn btn-lg btn-outline-dark rounded"
                    type="submit">Submit</button>
            </my-5>
        </form>
    </div>
</div>

{% endblock content %}

{% block scripts %}
<script>
    $(document).ready(function () {
        $("#id_time_granted_from, #id_time_granted").on("change", function () {
            var startDate = new Date($("#id_time_granted_from").val());
            var numberOfDays = parseInt($("#id_time_granted").val());

            if (!isNaN(startDate.getTime()) && !isNaN(numberOfDays)) {
                var endDate = new Date(startDate);
                endDate.setDate(startDate.getDate() + numberOfDays);

                var endYear = endDate.getFullYear();
                var endMonth = (endDate.getMonth() + 1).toString().padStart(2, '0');
                var endDay = endDate.getDate().toString().padStart(2, '0');

                var formattedEndDate = `${endYear}-${endMonth}-${endDay}`;
                $("#id_time_granted_to").val(formattedEndDate);
            }
        });
    });
</script>
{% endblock scripts %}

app/templates/extensions/subsequentpermit_detail.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% load humanize %}

{% block head_title %}
{{object}}
{% endblock head_title %}

{% block content %}
<div class="p-lg-5">
    <div class="col-lg-8 mx-auto">
        <h1>{{object|capfirst}}</h1>
        <h3>{{object.address_in_st_lucia}}</h3>
        <hr>
        <div class="small text-muted text-end">
            <p>Updated at {{object.updated_at}}</p>
        </div>
        <hr>

        <div class="row"
            style="font-size: larger;">
            <div class="col-lg mx-auto">
                <div>
                    <span class="text-muted">Date:</span>
                    <span>{{object.created_at}}</span>
                </div>
                <br>
                
                {% if object.length_of_stay %}
                <div>
                    <span class="text-muted">length_of_stay:</span>
                    <span>{{object.length_of_stay}}</span>
                </div>
                <br>
                {% endif %}
                <div>
                    <span class="text-muted">time_granted:</span>
                    <span>{{object.time_granted}}</span>
                </div>
                <br>
                <div>
                    <span class="text-muted">time_granted_from:</span>
                    <span>{{object.time_granted_from}}</span>
                </div>
                <br>
                <div>
                    <span class="text-muted">time_granted_to:</span>
                    <span>{{object.time_granted_to}}</span>
                </div>
                <br>
                <div>
                    <span class="text-muted">granted_by:</span>
                    <span>{{object.granted_by.profile}}</span>
                </div>
                <br>

            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-lg mx-auto">
                <h1>Payments</h1>
                <hr>
                <form action="{% url 'add-enquiry-remark' object.pk %}"
                    method="post">
                    <div class="modal-body">
                        {% csrf_token %}
                        {{payment_form|crispy}}
                    </div>
                    <div class="modal-footer">
                        <button type="submit"
                            class="btn btn-lg btn-outline-dark rounded-pill px-5">Save
                            changes</button>
                    </div>
                </form>
                <br>
                {% for ob in object.subsequent_permit_payments.all %}
                <div
                    class="col-lg mx-auto px-4 py-3 mb-2 bg-secondary bg-opacity-25 rounded-4">
                    <span>{{ob.payment_amount}}</span>
                    <hr>
                    <div class="text-end">
                        <span>{{ob.created_by}} <span
                                class="small text-muted">{{ob.created_at|naturaltime}}</span></span>
                    </div>
                </div>
                {% empty %}
                <p class="text-center">No remarks</p>
                {% endfor %}
            </div>
        </div>
    </div>
</div>


<!-- Modal -->
<div class="modal fade"
    id="exampleModal{{object.pk}}"
    tabindex="-1"
    aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5"
                    id="exampleModalLabel">{{object}}</h1>
                <button type="button"
                    class="btn-close"
                    data-bs-dismiss="modal"
                    aria-label="Close"></button>
            </div>


        </div>
    </div>
</div>

{% endblock content %}

app/templates/extensions/subsequentpermit_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block head_title %}
Form
{% endblock head_title %}


{% block content %}
<div class="container">
    <h1>Form</h1>
    <hr>
    <div class="col-lg-6 mx-auto p-5 m-5 rounded-4 shadow">
        <form action=""
            method="post"
            enctype="multipart/form-data">
            {% csrf_token %}
            {{form|crispy}}
            <my-5 class="my-5 d-grid">
                <button class="btn btn-lg btn-outline-dark rounded"
                    type="submit">Submit</button>
            </my-5>
        </form>
    </div>
</div>

{% endblock content %}

{% block scripts %}
<script>
    $(document).ready(function () {
        $("#id_time_granted_from, #id_time_granted").on("change", function () {
            var startDate = new Date($("#id_time_granted_from").val());
            var numberOfDays = parseInt($("#id_time_granted").val());

            if (!isNaN(startDate.getTime()) && !isNaN(numberOfDays)) {
                var endDate = new Date(startDate);
                endDate.setDate(startDate.getDate() + numberOfDays);

                var endYear = endDate.getFullYear();
                var endMonth = (endDate.getMonth() + 1).toString().padStart(2, '0');
                var endDay = endDate.getDate().toString().padStart(2, '0');

                var formattedEndDate = `${endYear}-${endMonth}-${endDay}`;
                $("#id_time_granted_to").val(formattedEndDate);
            }
        });
    });
</script>
{% endblock scripts %}